org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.warning.mode=all

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.1.3)
neo_version=26.1.2.21-beta
neo_version_range=[26.1.2.21-beta,)
java_version=25

ae2_version=26.1.8-alpha
ae2_version_range=[26.1.8-alpha,27.0.0)
junit_version=5.12.2

mod_id=controllerplus
mod_name=Controller+
mod_license=GPL-3.0-only
mod_version=0.1.0
mod_group_id=com.excal1bur
mod_authors=Excal1bur
mod_description=Adds specialised ME Controller variants to Applied Energistics 2, beginning with a configurable self-powered controller.
